// Generated by CoffeeScript 1.9.3
(function() {
  var commonDB;

  commonDB = require('./commonDatabaseFiles');

  module.exports = function(client, connection) {

    /* helper functions start */
    var addConfidantCount, addGameScore, addGamesReviewed, calculateAllReviewForGame, calculateNewPeers, calculateNewPros, calculateProReviewForGame, caluclatePeerReviewsForGame, confidantList, getGamesForUser, getGamesForUserOnPlatform, getGurusGameForUser, getOrCreateProReviewer, getPeersGameForUser, getProLibrary, getPros, getRecentReleases, getReviewLinksForProReviewers, isGameInLibrary, updateGameList;
    calculateNewPros = function(userId) {
      var sql;
      sql = 'call calculateNewPros(' + userId + ')';
      return connection.query(sql, userId, function(err, results) {});
    };
    calculateNewPeers = function(userId) {
      var sql;
      sql = 'call calculateNewPeers(' + userId + ')';
      return connection.query(sql, function(err, results) {});
    };
    calculateProReviewForGame = function(gameid, userid, callback) {
      var sql;
      sql = 'Select avg(rating) as rating , avg(enjoyment) as enjoyment ,  avg(unenjoyment) as unenjoyment , avg(difficulty) as difficulty, avg(length) as length  from ProReviewerLibrary prl ,userToProreviewer utp  where prl.id = utp.reviewer_id and utp.user_id=' + userid + ' and prl.game_id = ' + gameid;
      return connection.query(sql, [data.id], function(err, result) {
        return callback(result[0]);
      });
    };
    caluclatePeerReviewsForGame = function(gameid, userid, callback) {
      var sql;
      sql = 'Select avg(rating) as rating , avg(enjoyment) as enjoyment ,  avg(unenjoyment) as unenjoyment , avg(difficulty) as difficulty ,  avg(length) as length  from library prl , userToReviewers utp  where prl.id = utp.reviewer_id and utp.user_id=' + userid + ' and prl.game_id = ' + gameid;
      return connection.query(sql, [data.id], function(err, result) {
        return callback(result[0]);
      });
    };
    calculateAllReviewForGame = function(gameid, callback) {
      var sql;
      sql = 'Select avg(rating) as rating , avg(enjoyment) as enjoyment ,  avg(unenjoyment) as unenjoyment , avg(difficulty) as difficulty ,  avg(length) as length  from library l where l.game_id = ' + gameid;
      return connection.query(sql, [data.id], function(err, result) {
        return callback(result[0]);
      });
    };
    getReviewLinksForProReviewers = function(gameid, callback) {
      var sql;
      sql = 'Select review_link from ProReviewerLibrary prl ,userToProreviewer utp  where prl.id = utp.reviewer_id and utp.user_id=' + userid + ' and prl.game_id = ' + gameid;
      return connection.query(sql, [data.id], function(err, result) {
        return callback(result);
      });
    };
    getOrCreateProReviewer = function(data, callback) {
      var sql;
      sql = 'Select count(*) as reviewerCount ,id from ProReviewers where name = "' + data.name + '"';
      return connection.query(sql, function(err, result) {
        var firstresult;
        firstresult = result[0];
        if (firstresult.reviewerCount > 0) {
          return callback(firstresult.id);
        } else {
          sql = 'Insert into ProReviewers Set ?';
          return connection.query(sql, data, function(err, result) {
            var gameid;
            gameid = result.insertId;
            return callback(gameid);
          });
        }
      });
    };
    getRecentReleases = function(userid, client) {
      var sql;
      sql = 'select  count(*) as count from  userToReviewers  where user_id=' + userid;
      return connection.query(sql, function(err, result) {
        if (result[0].count > 0) {
          sql = 'Select * from ';
          sql += '(select  g.game_name , g.game_picture, g.id, g.giantBomb_id,g.releasedate, UNIX_TIMESTAMP(g.releasedate) as date   from  games g order by date desc) t1  ';
          sql += ' join (Select avg (peer.rating) as peerscore, peer.game_id from library peer, userToReviewers utr where  utr.reviewer_id = peer.user_id and peer.rating != -1 and utr.user_id = ' + userid + ' group by peer.game_id ) t2 ';
          sql += 'on t1.id = t2.game_id left  join (Select avg (pro.rating) as guruscore, pro.game_id from ProReviewerLibrary pro, userToProreviewer utr where  utr.reviewer_id = pro.user_id and utr.user_id = ' + userid + ' group by pro.game_id  ) t3 ';
          sql += 'on t3.game_id = t1.id order by t1.date desc limit 10';
          return connection.query(sql, function(err, result) {
            return client.emit('recentReleases', result);
          });
        } else {
          return client.emit('noGames');
        }
      });
    };
    getGurusGameForUser = function(userid, client, platform) {
      var sql;
      sql = 'call getGamesForUserOnplatform(' + userid + ',"' + platform + '" )';
      return connection.query(sql, function(err, result) {
        return client.emit('guruLibraryFound', result);
      });
    };
    getPeersGameForUser = function(userid, client, platform) {
      var sql;
      sql = 'call getGamesForUserOnplatform(' + userid + ',"' + platform + '" )';
      return connection.query(sql, function(err, result) {
        return client.emit('peerLibraryFound', result);
      });
    };
    getGamesForUserOnPlatform = function(userid, client, platform) {};
    getGamesForUser = function(username, localuserid, client) {
      var library, sql;
      library = {};
      sql = 'Select id,name,site,stream, picture from user where name = "' + username + '"';
      return connection.query(sql, function(err, result) {
        var user, userid;
        if (result.length <= 0) {
          return client.emit('noLibraryFound');
        } else {
          userid = result[0].id;
          user = result;
          library.myLibrary = userid === localuserid;
          sql = 'Select * from ';
          sql += '(select l.rating,l.added, g.id, l.description, g.giantBomb_id,g.releasedate, UNIX_TIMESTAMP(g.releasedate) as date  , g.game_name , g.game_picture from library l, games g where l.game_id = g.id and l.user_id =' + userid + ' order by date desc ) t1 ';
          sql += 'left join (Select avg (peer.rating) as peerscore, peer.game_id from library peer, userToReviewers utr where  utr.reviewer_id = peer.user_id  and peer.rating != -1 and utr.user_id = ' + userid + ' group by peer.game_id ) t2 ';
          sql += 'on t1.id = t2.game_id left join (Select avg (pro.rating) as guruscore, pro.game_id from ProReviewerLibrary pro, userToProreviewer utr where  utr.reviewer_id = pro.user_id and utr.user_id = ' + userid + ' group by pro.game_id ) t3 ';
          sql += 'on t3.game_id = t1.id';
          console.log(userid);
          return connection.query(sql, function(err, result) {
            library.games = result;
            library.user = user;
            return client.emit('gameLibraryFound', library);
          });
        }
      });
    };
    addGameScore = function(userid, gameid, bombid, callback) {
      var sql;
      sql = 'Select * from ';
      sql += '(select g.id, g.giantBomb_id,g.releasedate   from  games g where g.giantBomb_id  = ' + bombid + ') t1 ';
      sql += 'left join (Select avg (peer.rating) as peerscore, peer.game_id from library peer, userToReviewers utr where  utr.reviewer_id = peer.user_id and peer.rating != -1 and utr.user_id = ' + userid + '  and peer.game_id =' + gameid + ' ) t2 ';
      sql += 'on t1.id = t2.game_id left join (Select avg (pro.rating) as guruscore, pro.game_id from ProReviewerLibrary pro, userToProreviewer utr where  utr.reviewer_id = pro.user_id and utr.user_id = ' + userid + ' and pro.game_id =' + gameid + ' ) t3 ';
      sql += 'on t3.game_id = t1.id';
      return connection.query(sql, function(err, result) {
        console.log(result);
        return callback(result);
      });
    };
    updateGameList = function(userid, gamelist, index, callback) {
      var game, length, sql;
      length = gamelist.length;
      if (index < length) {
        game = gamelist[index];
        sql = 'select g.id, count(*) as count from  games g where g.giantBomb_id  =' + game.id;
        return connection.query(sql, function(err, result) {
          if (result[0].count === 0) {
            return updateGameList(userid, gamelist, index + 1, callback);
          } else {
            return addGameScore(userid, result[0].id, game.id, function(results) {
              if (results) {
                game.details = results[0];
                gamelist[index] = game;
              }
              return updateGameList(userid, gamelist, index + 1, callback);
            });
          }
        });
      } else {
        return callback(gamelist);
      }
    };

    /*helper functions end */
    client.on('GetLibrary', function(username) {
      return getGamesForUser(username, client.userid, client);
    });
    client.on('updateGameInLibrary', function(data) {
      var sql;
      sql = ' Update library Set ? where id =' + data.id;
      return connection.query(sql, data, function(err, result) {
        console.log('game updated');
        return getGamesForUser(client.username, client.userid, client);
      });
    });
    client.on('GetGuruLibrary', function(platform) {
      return getGurusGameForUser(client.userid, client, platform);
    });
    client.on('GetPeerLibrary', function(platform) {
      return getPeersGameForUser(client.userid, client, platform);
    });
    isGameInLibrary = function(data, callback) {
      var sql;
      sql = 'select count(*) as count from library l where l. user_id =' + data.user_id + ' and game_id = ' + data.game_id;
      return connection.query(sql, function(err, results) {
        if (results[0].count === 0) {
          return callback(false);
        } else {
          return callback(true);
        }
      });
    };
    client.on('AddNewGameToLibrary', function(data) {
      commonDB.connection = connection;
      return commonDB.getOrCreateGame(data.giantBombinfo, data.platforms, function(gameid) {
        data.userInfo.game_id = gameid;
        data.userInfo.user_id = client.userid;
        return isGameInLibrary(data.userInfo, function(results) {
          var sql;
          if (!results) {
            sql = 'Insert into library Set ?';
            return connection.query(sql, data.userInfo, function(err, results) {
              calculateNewPeers(data.userInfo.user_id);
              calculateNewPros(data.userInfo.user_id);
              return getGamesForUser(client.username, client.userid, client);
            });
          }
        });
      });
    });
    client.on('GetNewGameReviews', function() {
      var sql;
      sql = 'Select * from games where 1 sort by added Desc limit 10';
      return connection.query(sql, function(err, result) {
        var gameid, games, i, len, res;
        games = [];
        for (i = 0, len = result.length; i < len; i++) {
          res = result[i];
          gameid = res['id'];
          res['peerReview'] = caluclatePeerReviewsForGame(gameid);
          res['proReview'] = calculateProReviewForGame(gameid);
          games.push(res);
        }
        return client.emit('recentGames', games);
      });
    });
    client.on('GetReviewForGame', function(gameid) {
      var sql;
      sql = 'Select * from games where id = ? ';
      return connection.query(sql, [gameid], function(err, result) {
        result['peerReview'] = caluclatePeerReviewsForGame(gameid);
        result['proReview'] = calculateProReviewForGame(gameid);
        return client.emit('gameReview', result);
      });
    });
    client.on('deleteGame', function(game) {
      var sql;
      sql = 'delete from library where game_id =' + game.id + ' and user_id=' + client.userid;
      return connection.query(sql, [gameid], function(err, result) {
        return getGamesForUser(client.username, client.userid, client);
      });
    });
    client.on('updateGame', function(game) {
      var sql;
      sql = 'Update library set rating =' + game.rating + ', description = "' + game.description + '" where game_id =' + game.id + ' and user_id=' + client.userid;
      console.log(sql);
      return connection.query(sql, function(err, result) {
        return getGamesForUser(client.username, client.userid, client);
      });
    });
    client.on('searchForGames', function(games) {
      return updateGameList(client.userid, games.list, 0, function(newlist) {
        return client.emit('searchfinished', newlist);
      });
    });
    client.on('getGuruDetails', function(gameid) {
      var sql;
      sql = 'Select g.game_name as name, pr.name as reviewerName, prl.true_score as score, prl.true_score_max as scoremax, prl.review_link as reviewlink from userToProreviewer utp, ProReviewerLibrary prl ,games g , ProReviewers pr where utp.user_id =' + client.userid + ' and utp.reviewer_id = pr.id and g.id =' + gameid.gameid + ' and prl.user_id = utp.reviewer_id and g.id = prl.game_id';
      return connection.query(sql, function(err, result) {
        return client.emit('guruDetailsFound', result);
      });
    });
    client.on('getPeerDetails', function(gameid) {
      var sql;
      sql = 'Select g.game_name as name, pr.name as reviewerName, prl.rating as score, prl.description as details from userToReviewers utp, library prl, games g , user pr where utp.user_id =' + client.userid + ' and utp.reviewer_id = pr.id and g.id =' + gameid.gameid + ' and prl.user_id = utp.reviewer_id and g.id = prl.game_id';
      return connection.query(sql, function(err, result) {
        console.log(result);
        return client.emit('peerDetailsFound', result);
      });
    });
    getPros = function() {
      var sql;
      sql = 'Select * from ProReviewers  where active = 1';
      return connection.query(sql, function(err, result) {
        console.log(result);
        return client.emit('ProreviewersFound', result);
      });
    };
    client.on('GetRecentGames', function() {
      return getRecentReleases(client.userid, client);
    });
    client.on('GetProreviewers', function(data) {
      return getPros();
    });
    client.on('addPro', function(data) {
      var sql;
      sql = 'Insert into ProReviewers Set ?';
      return connection.query(sql, data, function(err, result) {
        return getPros();
      });
    });
    client.on('ProReviewers', function(data) {
      var sql;
      sql = 'Update library set site_address =' + data.site_address + ', name = "' + data.name + '" where id =' + data.id;
      return connection.query(sql, [gameid], function(err, result) {
        return getPros();
      });
    });
    getProLibrary = function(id) {
      var sql;
      sql = 'Select * from  ProReviewerLibrary pr, games g where g.id=pr.game_id and pr.user_id =' + id;
      console.log(sql);
      return connection.query(sql, function(err, result) {
        return client.emit('ProLibrarysFound', result);
      });
    };
    client.on('GetListOfPlatforms', function(data) {
      var sql;
      sql = 'Select display_name from platforms where active =1 group by display_name order by relevanceRanking';
      return connection.query(sql, function(err, result) {
        return client.emit('platformsFound', result);
      });
    });
    client.on('UpdateUserLibraryInfo', function(data) {
      var sql;
      sql = "Update user set site ='" + data.site + "', stream='" + data.stream + "' where id =" + client.userid;
      return connection.query(sql, function(err, result) {});
    });
    client.on('GetProreviewerLibrary', function(data) {
      return getProLibrary(data.id);
    });
    client.on('AddNewProGameToLibrary', function(data) {
      commonDB.connection = connection;
      return commonDB.getOrCreateGame(data.giantBombinfo, data.platforms, function(gameid) {
        var sql;
        data.userInfo.game_id = gameid;
        sql = 'Insert into ProReviewerLibrary  Set ?';
        return connection.query(sql, data.userInfo, function(err, results) {
          return getProLibrary(data.userInfo.user_id);
        });
      });
    });
    client.on('updateGamePlatforms', function(data) {
      var i, len, platform, ref, results1;
      ref = data.platforms;
      results1 = [];
      for (i = 0, len = ref.length; i < len; i++) {
        platform = ref[i];
        results1.push(commonDB.getOrCreatePlatform(platform.abbreviation, data.id, connection));
      }
      return results1;
    });
    client.on('AddGameandReviewerToLibrary', function(data) {
      commonDB.connection = connection;
      return commonDB.getOrCreateGame(data.giantBombinfo, data.platforms, function(gameid) {
        return getOrCreateProReviewer(data.pro, function(newuserid) {
          var sql;
          data.userInfo.game_id = gameid;
          data.userInfo.user_id = newuserid;
          sql = 'Select count(*) as gamecount from ProReviewerLibrary where game_id = ' + gameid + ' and user_id=' + newuserid;
          return connection.query(sql, [data.giantBomb_id], function(err, result) {
            var firstresult;
            client.emit('finishedInsert');
            firstresult = result[0];
            if (firstresult.gamecount === 0) {
              sql = 'Insert into ProReviewerLibrary  Set ?';
              return connection.query(sql, data.userInfo, function(err, results) {
                gameid = result.insertId;
                sql = 'call updateFakeUsers (' + gameid + ',' + gameid + ')';
                return connection.query(sql, function(err, results) {});
              });
            }
          });
        });
      });
    });
    confidantList = function() {
      var sql;
      sql = 'Select count(*) as friendsCount, u.name, u.site, u.picture, u.stream, u.id from user u, userToFriends uf where u.id = uf.friend_id and  uf.user_id =' + client.userid;
      return connection.query(sql, function(err, result) {
        var firstresult, resultLength;
        firstresult = result[0];
        if (firstresult.friendsCount === 0) {
          return client.emit('noFriendsFound');
        } else {
          resultLength = result.length;
          return addConfidantCount(result, 0, resultLength, function(userlistWithConfidants) {
            return addGamesReviewed(userlistWithConfidants, 0, resultLength, function(finalUserList) {
              return client.emit('listOfFriends', finalUserList);
            });
          });
        }
      });
    };
    client.on('GetConfidants', function() {
      return confidantList();
    });
    client.on('AddConfidant', function(data) {
      var sql;
      sql = 'Select Count(*) as doesRelationshipExist from userToFriends where user_id=' + client.userid + ' and friend_id =' + data.friendid;
      return connection.query(sql, function(err, result) {
        if (result[0].doesRelationshipExist === 0) {
          sql = 'Insert into userToFriends (user_id, friend_id) values(' + client.userid + ',' + data.friendid + ')';
          console.log(sql);
          return connection.query(sql, function(err, result) {
            return confidantList();
          });
        }
      });
    });
    addConfidantCount = function(userlist, index, length, callback) {
      var sql;
      if (index === length) {
        return callback(userlist);
      } else {
        sql = 'Select Count(*) as confidantCount from userToFriends where friend_id=' + userlist[index].id;
        return connection.query(sql, function(err, result) {
          userlist[index].confidantCount = result[0].confidantCount;
          return addConfidantCount(userlist, index + 1, length, callback);
        });
      }
    };
    addGamesReviewed = function(userlist, index, length, callback) {
      var sql;
      if (index === length) {
        return callback(userlist);
      } else {
        sql = 'Select Count(*) as reviews from library where user_id=' + userlist[index].id;
        return connection.query(sql, function(err, result) {
          userlist[index].reviews = result[0].reviews;
          return addGamesReviewed(userlist, index + 1, length, callback);
        });
      }
    };
    return client.on('SearchForConfidants', function(data) {
      var sql;
      sql = 'Select count(*) as friendsCount, u.name, u.site, u.stream, u.picture, u.id from user u where u.name like ' + connection.escape('%' + data.search + '%');
      return connection.query(sql, function(err, result) {
        var firstresult, resultLength;
        firstresult = result[0];
        if (firstresult.friendsCount === 0) {
          return client.emit('noUsersFound');
        } else {
          resultLength = result.length;
          return addConfidantCount(result, 0, resultLength, function(userlistWithConfidants) {
            return addGamesReviewed(userlistWithConfidants, 0, resultLength, function(finalUserList) {
              return client.emit('listofPossibleConfidants', finalUserList);
            });
          });
        }
      });
    });
  };

}).call(this);
