// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(client, request) {
    var giantbombInfo;
    giantbombInfo = {};
    giantbombInfo.apikey = 'api_key=059d37ad5ca7f47e566180366eab2190e8c6da30';
    giantbombInfo.baseurl = 'http://www.giantbomb.com/api/';
    giantbombInfo.fiedList = '&field_list=name,image,id,deck,original_release_date,platforms,genres&resources=game&format=jsonp&json_callback=JSON_CALLBACK';
    giantbombInfo.searchPath = 'search/?';
    giantbombInfo.gamePath = 'game/';
    client.on('findGamesInWiki', function(game) {
      var GameSearchURL;
      GameSearchURL = giantbombInfo.baseurl + giantbombInfo.searchPath + giantbombInfo.apikey + '&query=' + game + giantbombInfo.fiedList;
      return request(GameSearchURL, function(error, response, body) {
        var data, endPos, jsonString, startPos;
        data = '';
        if (!error && response.statusCode === 200) {
          startPos = body.indexOf('({');
          endPos = body.indexOf('})');
          jsonString = body.substring(startPos + 1, endPos + 1);
          data = JSON.parse(jsonString);
          return client.emit('listOfGamesFromWiki', data);
        } else {
          return console.log(error);
        }
      });
    });
    return client.on('getGameInfoFromWiki', function(gameid) {
      var GameSearchURL;
      GameSearchURL = giantbombInfo.baseurl + giantbombInfo.gamePath + gameid + '/?' + giantbombInfo.apikey + giantbombInfo.fiedList;
      return request(GameSearchURL, function(error, response, body) {
        var data, endPos, jsonString, startPos;
        if (!error && response.statusCode === 200) {
          startPos = body.indexOf('({');
          endPos = body.indexOf('})');
          jsonString = body.substring(startPos + 1, endPos + 1);
          data = JSON.parse(jsonString);
          return client.emit('gameInfoForGameFromWiki', data);
        } else {
          return console.log(error);
        }
      });
    });
  };

}).call(this);
